name: vitask
description: A new Flutter application.

version: 2.1.0+9

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  animated_text_kit: ^4.2.1
  http: ^0.13.3
  modal_progress_hud: ^0.1.3
  sembast: ^3.1.0+2
  path_provider: ^2.0.2
  flutter_circular_chart: ^0.1.0
  font_awesome_flutter: ^9.1.0
  flutter_local_notifications: ^8.1.1+1
  shared_preferences: ^2.0.6
  percent_indicator: ^3.0.1
  intl: ^0.17.0
  google_fonts: ^2.1.0
  auto_size_text: ^2.1.0
  progress_indicators: ^1.0.0
  fluttertoast: ^8.0.8
  flutter_keyboard_visibility: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/